export { default as Footer } from "./Footer";
export { default as Header } from "./Navbar";
export { default as Hero } from "./Hero";
export { default as About } from "./About";
export { default as Skills } from "./Skills";
export { default as Projects } from "./Projects";
export { default as Testimonials } from "./Testimonials";
export { default as HomePage } from "./HomePage";
export { default as TypingText } from "./TypingText";
